### PR TITLE
Update LA mayor

### PR DESCRIPTION
**Pull request by chris-erickson**
Karen Bass has a history in OS so I think I did it correctly.

### CODE REVIEW

**Review by NewAgeAirbender — CHANGES_REQUESTED** [review]
When you retire people, make sure you're setting an end date and removing their office location data like in this [pull request](https://github.com/openstates/people/pull/812/files). This will get the checks passing on this PR so it'll be good to merge!

**Comment by chris-erickson** [comment]
@NewAgeAirbender thanks for the help on that. Where can I find this updating function? I assumed it would be in a repo someplace but didn't see it after a quick search.

**Comment by NewAgeAirbender** [comment]
It's detailed in [OS core](https://github.com/openstates/openstates-core/blob/main/openstates/utils/people/retire.py), but if you wanted to use it in the case of this change, you'd run `poetry run os-people retire data/ca/municipalities/Eric-Garcetti-dff83234-6e33-490d-bc44-78779427c917.yml` in your terminal. It'll ask you for an end date if you didn't update it in that file already, move the file to the `/retire` folder, and remove the unnecessary data.

**Review by NewAgeAirbender — APPROVED** [review]

**Comment by chris-erickson** [comment]
@NewAgeAirbender we good to merge?

**Pull request merged**
