### PR TITLE
IL: Add legislators for 16th, 26th house district

### PR DESCRIPTION
**Pull request by estaub**
As I'm new to this process, these two new legislators need careful review. 

Related: https://github.com/openstates/openstates/issues/2821

### CODE REVIEW

**Comment by estaub** [comment]
The Travis failures are in other states (AZ and MN).

**Comment by csnardi** [comment]
#127 should include these changes along with a much broader update of all Illinois legislator information.

**Comment by koryp123** [comment]
the following legislators need review/updated/added:

Bob Morgan (rep)
Gregory Harris (rep)
Terra Costa Howard (rep)
Debbie Meyers-Martin
Patricia Van Pelt
John Cullerton (sen)
William Cunningham (sen)
Julie Morrison (sen)
Steven Landek (sen)
Don Harmon (sen)
Robert Peters (sen)
Jacqueline Collins (sen)
Iris Martinez (sen)
John Mulroe (sen)
Dan McConchie (sen)
Michael Hastings (sen)
Terry Link (sen)
Elgie Sims (sen)
Ram Villivalam (sen)
Heather Steans (sen)
Toi Hutchison (sen)
Laura Murphy (sen)
Kimberly Lightford (sen)

**Comment by estaub** [comment]
@koryp123 See https://github.com/openstates/people/pull/127.  You might want to check the diffs to see if they address what you know of.

**Pull request closed without merging**
