### PR TITLE
Updates to Ohio legislator data

### PR DESCRIPTION
**Pull request by csnardi**
Mostly contact information changes. One legislator was added (appointed to House), one legislator retired (appointed to position), and one House member was appointed to the Senate.

### CODE REVIEW

**Comment by csnardi** [comment]
@jamesturk Do you think some of these PRs could be merged in (or perhaps another person could be added with write access who could do that)?

**Comment by csnardi** [comment]
@jamesturk Any thoughts? Maybe the latter would be helpful to reduce the amount of work you need to do?

**Comment by jamesturk** [comment]
Sorry I've been out of town, looks like tests are failing due to vacancies
but if there's a PR to fix that (or once I'm home with a laptop) I can
merge it

**Comment by csnardi** [comment]
@jamesturk Several of these PRs address the failing lints (though not completely) so I think some PRs would need to be combined to make the checks all pass. I can do that if needed

**Pull request merged**
