### PR TITLE
MA: Abbreviate lower districts

### PR DESCRIPTION
**Pull request by bhrutledge**
Following up on https://github.com/openstates/openstates-scrapers/pull/3476, per comments from @jamesturk.

### CODE REVIEW

**Comment by bhrutledge** [comment]
Tracing backing from `Lint YAML` error, it looks like:

- District names need to be updated in https://github.com/openstates/openstates-core/blob/main/openstates/metadata/_creation/settings.yml
- Followed by running https://github.com/openstates/openstates-core/blob/main/openstates/metadata/_creation/write_data.py
    - Possibly via https://github.com/openstates/openstates-core/blob/main/openstates/metadata/_creation/create_data.sh
    - Which should update https://github.com/openstates/openstates-core/blob/main/openstates/metadata/data/ma.py
- Followed by a PyPI release of the `openstates` package

Is that correct? Any tips for going through that process?

**Comment by jamesturk** [comment]
That looks right, but we haven't done a district change like this before with this system so bear with me as I try to make sure that we aren't leaving anything out.

**Comment by jamesturk** [comment]
I'll add, If you have any trouble with create_data.sh I can take a PR that just has the settings.yml updated and work it out from there

**Comment by bhrutledge** [comment]
Thanks, @jamesturk. Now that I've gotten a sense of how deep this rabbit hole goes, I think it's worth a quick sanity check on the district rename. I still think it's a idea, but getting updated/accurate legislator data feels like a higher priority, esp. with a new session starting.

In short, would it make sense to revert https://github.com/openstates/openstates-scrapers/pull/3476 for now, update the data as discussed in https://github.com/openstates/issues/issues/207#issuecomment-751744203, and then revisit this once that's done? Or, should I finish what I've started? I could go either way.

Thanks for bouncing around all these threads with me.

**Comment by jamesturk** [comment]
I think we can get these both updated together if you're game for it!  openstates-core would be next, we could get that done before MA updates their roster probably so we're ready to go with the person update at the same(ish) time

**Comment by bhrutledge** [comment]
I opened https://github.com/openstates/openstates-core/pull/18 with the `metadata` changes.

**Comment by bhrutledge** [comment]
@jamesturk Thanks for publishing a new `openstates` release. I've updated this PR to use that, and tests and linting are now passing. 🕺

**Comment by bhrutledge** [comment]
@jamesturk I think I resolved the merge conflict from `pyproject.toml`. Assuming the checks pass, is there anything else that needs to be done before merge?

**Comment by jamesturk** [comment]
working on this today, it'll go in as part of #401 which includes the legislator updates

**Pull request merged**
