### PR TITLE
OK: Add image urls for upper chamber members

### PR DESCRIPTION
**Pull request by brybeecher**
OK: Add image urls for upper chamber members

### CODE REVIEW

**Comment by brybeecher** [comment]
@jamesturk :slightly_smiling_face:

**Comment by jamesturk** [comment]
this looks great, thanks!

**Comment by brybeecher** [comment]
@jamesturk would you mind briefly explaining (or pointing me to where it might be documented) what the process is after a PR is merged that leads to this data getting populated in the API? Curious if it is fully automated or a manual step is required and how long it takes. (I know you had said previously it takes ~1 day to show up.). Appreciate all the work you do!

**Comment by jamesturk** [comment]
I need to fix a small hiccup in that process, which I can do tomorrow.  But
typically it is waiting on a cron-like job to run and update it.  It'll be
a manual process this time since that system is being overhauled.

I think once it is fixed that job will run at least twice a day so the
maximum delay between merge to master and appearance in API is 12 hours.

**Comment by brybeecher** [comment]
Great, thanks for sharing!

**Pull request merged**
